"""add user settings

Revision ID: 2f0f06807e03
Revises: d5e3f9c4b2a7
Create Date: 2026-03-13 21:30:54.617974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2f0f06807e03'
down_revision: Union[str, None] = 'd5e3f9c4b2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
