"""add feedback table

Revision ID: 9436181edf93
Revises: aed0f1b7b895
Create Date: 2026-07-09 19:57:56.870014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '9436181edf93'
down_revision: Union[str, None] = 'aed0f1b7b895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('bug', 'idea', 'other')", name='ck_feedback_category'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False, if_not_exists=True)
    # NOTE: autogenerate also emitted accountability-table drops + index drift
    # from a stale local DB — stripped; this migration is feedback-only.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_user_id', table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
