"""drop accountability tables

Revision ID: aed0f1b7b895
Revises: a4b5c6d7e8f9
Create Date: 2026-07-05 19:35:24.462348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aed0f1b7b895'
down_revision: Union[str, None] = 'a4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accountability_invites_invitee_status', table_name='accountability_invites')
    op.drop_index('ix_accountability_invites_inviter_status', table_name='accountability_invites')
    op.drop_index('ix_accountability_invites_target_email', table_name='accountability_invites')
    op.drop_table('accountability_invites')
    op.drop_index('ix_accountability_partnerships_user_id', table_name='accountability_partnerships')
    op.drop_table('accountability_partnerships')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountability_partnerships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('partner_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('user_id::text <> partner_user_id::text', name='ck_accountability_partners_not_self'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], name='accountability_partnerships_partner_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='accountability_partnerships_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='accountability_partnerships_pkey'),
    sa.UniqueConstraint('user_id', 'partner_user_id', name='uq_accountability_partnership_pair')
    )
    op.create_index('ix_accountability_partnerships_user_id', 'accountability_partnerships', ['user_id'], unique=False)
    op.create_table('accountability_invites',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inviter_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('invitee_user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying]::text[])", name='ck_accountability_invite_status'),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], name='accountability_invites_invitee_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], name='accountability_invites_inviter_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='accountability_invites_pkey')
    )
    op.create_index('ix_accountability_invites_target_email', 'accountability_invites', ['target_email'], unique=False)
    op.create_index('ix_accountability_invites_inviter_status', 'accountability_invites', ['inviter_user_id', 'status'], unique=False)
    op.create_index('ix_accountability_invites_invitee_status', 'accountability_invites', ['invitee_user_id', 'status'], unique=False)
    # ### end Alembic commands ###
