import { useEffect, useState } from 'react'
import SiteHeader from '../components/SiteHeader'
import SiteFooter from '../components/SiteFooter'
import '../landing.css'

export default function TermsPage() {
  const [theme] = useState<'light' | 'dark'>(() => {
    const saved = window.localStorage.getItem('gf-landing-theme')
    return saved === 'dark' ? 'dark' : 'light'
  })
  useEffect(() => { document.title = 'Terms of Service · GoalForge' }, [])

  return (
    <div className="gfl-root gfl-static" data-theme={theme}>
      <div className="wrap">
        <SiteHeader />
        <main className="container static-main">
          <section className="about-section">
            <h1>Terms of Service</h1>
            <p className="legal-updated">Last updated: July 13, 2026</p>
            <p>
              These terms are the agreement between you and GoalForge
              (goalforge.me), a goal-tracking service built by Samat
              Kerimkulov. By creating an account or using GoalForge, you agree
              to them. They are written to be read, not just scrolled past —
              please do.
            </p>
          </section>

          <section className="about-section">
            <h2>The service</h2>
            <p>
              GoalForge turns goals you describe into structured plans with
              milestones and daily tasks, tracks your progress, and includes
              Solly, an AI coach. GoalForge is currently in early access and
              free to use. We may introduce paid tiers later; if that happens,
              we will say so clearly before anything changes for you.
            </p>
          </section>

          <section className="about-section">
            <h2>Your account</h2>
            <p>
              You need an account to use GoalForge, created through our
              authentication provider, Clerk. You are responsible for activity
              that happens under your account, and you agree to provide
              accurate sign-up information. You must be at least 13 years old
              (or the minimum age of digital consent in your country) to use
              GoalForge.
            </p>
          </section>

          <section className="about-section">
            <h2>AI-generated content</h2>
            <p>
              Plans, tasks, and coach replies in GoalForge are generated by AI.
              They can be wrong, incomplete, or a bad fit for your situation.
              They are suggestions to help you organize your own effort — not
              medical, legal, financial, fitness, or other professional advice.
              For decisions that matter to your health, money, or legal
              standing, talk to a qualified professional. You are always free
              to edit, regenerate, or ignore anything the AI produces.
            </p>
          </section>

          <section className="about-section">
            <h2>Your content</h2>
            <p>
              The goals, tasks, and messages you create belong to you. You give
              GoalForge permission to store and process them solely to provide
              the service — for example, sending your goal text to our AI
              provider to generate a plan. We do not sell your content or use
              it to train AI models. You can export or delete everything from
              Settings at any time.
            </p>
          </section>

          <section className="about-section">
            <h2>Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>use GoalForge for anything unlawful, or to create content that harms others;</li>
              <li>attempt to break, overload, probe, or gain unauthorized access to the service;</li>
              <li>abuse the AI features, including attempts to extract system prompts or bypass safety measures;</li>
              <li>resell or scrape the service, or use it to build a competing dataset.</li>
            </ul>
            <p>
              We may suspend or terminate accounts that violate these terms.
              You can stop using GoalForge at any time by deleting your account
              data from Settings.
            </p>
          </section>

          <section className="about-section">
            <h2>Disclaimers and liability</h2>
            <p>
              GoalForge is provided &quot;as is&quot; and &quot;as
              available&quot;, without warranties of any kind, express or
              implied. It is an early-access product run by one person —
              outages, bugs, and rough edges can happen, and we do not
              guarantee the service will be uninterrupted or error-free. To the
              maximum extent permitted by law, GoalForge and its creator are
              not liable for indirect, incidental, or consequential damages
              arising from your use of the service, and total liability for any
              claim is limited to the amount you paid us in the twelve months
              before the claim (currently: nothing, since GoalForge is free).
            </p>
          </section>

          <section className="about-section">
            <h2>Changes to these terms</h2>
            <p>
              We may update these terms as GoalForge evolves. If a change is
              significant, we will update the date at the top and let you know
              in the app or by email. Continuing to use GoalForge after a
              change means you accept the updated terms.
            </p>
          </section>

          <section className="about-section">
            <h2>Contact</h2>
            <p>
              Questions about these terms? Email{' '}
              <a href="mailto:goalforge65@gmail.com">goalforge65@gmail.com</a>.
            </p>
          </section>
        </main>
        <SiteFooter />
      </div>
    </div>
  )
}
