/**
 * GoalForge API — Auto-generated TypeScript types
 *
 * ⚠️  DO NOT EDIT MANUALLY — this file is generated by openapi-typescript.
 * To regenerate: npm run generate:types  (requires running API server)
 *
 * Setup: npm install  (adds openapi-typescript + openapi-fetch)
 * CI:    Run API server → npm run generate:types → commit if diff detected
 */

export interface paths {
  "/users/{user_id}/profile": {
    get: operations["get_user_profile"]
  }
  "/users/{user_id}/settings": {
    get: operations["get_user_settings"]
    patch: operations["update_user_settings"]
  }
  "/users/{user_id}/goals": {
    get: operations["list_goals"]
    post: operations["create_goal"]
  }
  "/goals/{goal_id}": {
    get: operations["get_goal"]
    patch: operations["update_goal_status"]
    delete: operations["delete_goal"]
  }
  "/goals/{goal_id}/progress": {
    patch: operations["update_goal_progress"]
  }
  "/goals/{goal_id}/rescue": {
    post: operations["trigger_rescue_sprint"]
  }
  "/goals/{goal_id}/tasks": {
    get: operations["list_goal_tasks"]
    post: operations["create_task"]
  }
  "/goals/{goal_id}/tasks/reorder": {
    put: operations["reorder_tasks"]
  }
  "/goals/{goal_id}/milestones/{milestone_id}/complete": {
    post: operations["complete_milestone"]
  }
  "/goals/{goal_id}/milestones/{milestone_id}/retry-generation": {
    post: operations["retry_milestone_generation"]
  }
  "/tasks/{task_id}/complete": {
    patch: operations["complete_task"]
  }
  "/tasks/{task_id}": {
    patch: operations["update_task"]
    delete: operations["delete_task"]
  }
  "/tasks/{task_id}/regenerate": {
    post: operations["regenerate_task"]
  }
  "/users/{user_id}/coach/sessions/start": {
    post: operations["start_coach_session"]
  }
  "/users/{user_id}/coach/sessions/active": {
    get: operations["get_active_coach_session"]
  }
  "/coach/sessions/{session_id}/messages": {
    post: operations["send_coach_message"]
  }
  "/users/{user_id}/rewards": {
    get: operations["list_rewards"]
  }
  "/rewards/{reward_id}/equip": {
    patch: operations["equip_reward"]
  }
  "/users/{user_id}/shop-rewards": {
    get: operations["list_shop_rewards"]
    post: operations["create_shop_reward"]
  }
  "/shop-rewards/{reward_id}": {
    patch: operations["update_shop_reward"]
    delete: operations["delete_shop_reward"]
  }
  "/shop-rewards/{reward_id}/redeem": {
    post: operations["redeem_shop_reward"]
  }
  "/users/{user_id}/accountability-invites": {
    get: operations["get_accountability_overview"]
    post: operations["send_accountability_invite"]
  }
  "/accountability-invites/{invite_id}/accept": {
    post: operations["accept_accountability_invite"]
  }
  "/accountability-invites/{invite_id}/decline": {
    post: operations["decline_accountability_invite"]
  }
  "/users/{user_id}/weekly-reflection": {
    post: operations["create_weekly_reflection"]
  }
  "/users/{user_id}/weekly-reflection/latest": {
    get: operations["get_latest_weekly_reflection"]
  }
  "/users/{user_id}/weekly-review": {
    get: operations["get_weekly_review"]
  }
  "/users/{user_id}/star-log": {
    get: operations["get_star_log"]
  }
  "/users/{user_id}/badges": {
    get: operations["get_user_badges"]
  }
  "/users/{user_id}/export": {
    get: operations["export_user_data"]
  }
  "/users/{user_id}": {
    delete: operations["delete_user"]
  }
}

export interface components {
  schemas: {
    UserProfile: {
      /** User's Clerk ID */
      id: string
      email: string
      star_points: number
      display_name: string | null
      timezone: string
      reminder_enabled: boolean
      reminder_hour: number
    }
    UserSettingsUpdate: {
      display_name?: string | null
      reminder_enabled?: boolean | null
      /** 0–23 */
      reminder_hour?: number | null
    }
    Goal: {
      id: string
      user_id: string
      raw_input: string
      smart_title: string
      smart_description: string
      goal_type: string
      target_date: string
      status: "active" | "achieved" | "abandoned"
      progress: number
      created_at: string
      milestones: components["schemas"]["Milestone"][]
      milestones_completed: number
      milestones_total: number
      daily_tasks: components["schemas"]["DailyTask"][]
      /** ISO date strings where at least one task was completed */
      completed_days: string[]
      rescue_mode: boolean
    }
    GoalCreate: {
      raw_input: string
    }
    GoalStatusUpdate: {
      status: "active" | "achieved" | "abandoned"
    }
    GoalProgressUpdate: {
      /** 0–100 */
      progress: number
    }
    Milestone: {
      id: string
      goal_id: string
      title: string
      position: number
      is_final: boolean
      sprint_theme: string
      sprint_status: "pending" | "generating" | "ready" | "active" | "completed" | "failed"
      is_completed: boolean
      completed_at: string | null
      generation_started_at: string | null
      created_at: string
    }
    DailyTask: {
      id: string
      goal_id: string
      milestone_id: string | null
      description: string
      tip: string
      assigned_date: string
      position: number
      is_completed: boolean
      completed_at: string | null
      is_rescue_task: boolean
      original_description: string | null
      original_tip: string | null
    }
    TaskCreate: {
      description: string
      milestone_id?: string | null
      assigned_date?: string | null
      tip?: string
    }
    TaskUpdate: {
      description: string
    }
    TaskReorderItem: {
      id: string
      position: number
    }
    TaskReorderRequest: {
      tasks: components["schemas"]["TaskReorderItem"][]
    }
    RewardDrop: {
      tier: "bonus" | "crit" | "jackpot"
      points_awarded: number
      collectible_type: "theme" | "title" | "lore" | null
      collectible_key: string | null
      collectible_display_name: string | null
      /** Lore text only; null for theme/title */
      collectible_body: string | null
    }
    TaskCompleteResponse: components["schemas"]["DailyTask"] & {
      reward_drop: components["schemas"]["RewardDrop"] | null
      points_awarded: number
    }
    EnergyResizeResponse: {
      tasks_resized: number
      tasks: components["schemas"]["DailyTask"][]
    }
    PaginatedGoalsResponse: {
      items: components["schemas"]["Goal"][]
      total: number
      limit: number
      offset: number
    }
    Reward: {
      id: string
      reward_type: "theme" | "title" | "lore"
      reward_key: string
      display_name: string
      body: string | null
      is_equipped: boolean
      acquired_at: string
    }
    ShopReward: {
      id: string
      user_id: string
      title: string
      cost: number
      is_active: boolean
      redemption_count: number
      created_at: string
    }
    ShopRewardCreate: {
      title: string
      cost: number
    }
    ShopRewardUpdate: {
      title?: string | null
      cost?: number | null
      is_active?: boolean | null
    }
    ShopRewardRedeemResponse: {
      reward: components["schemas"]["ShopReward"]
      remaining_star_points: number
    }
    CoachMessage: {
      id: string
      session_id: string
      role: "coach" | "user"
      content: string
      created_at: string
    }
    CoachSession: {
      id: string
      user_id: string
      stage: number
      is_completed: boolean
      forged_goal_id: string | null
      created_at: string
      updated_at: string
      messages: components["schemas"]["CoachMessage"][]
    }
    CoachSendMessageRequest: {
      content: string
    }
    CoachSendMessageResponse: {
      session: components["schemas"]["CoachSession"]
      forged_goal: components["schemas"]["Goal"] | null
    }
    AccountabilityInvite: {
      id: string
      inviter_user_id: string
      invitee_user_id: string | null
      target_email: string
      status: "pending" | "accepted" | "declined"
      created_at: string
      responded_at: string | null
      inviter_email: string | null
      inviter_display_name: string | null
    }
    AccountabilityPartner: {
      id: string
      user_id: string
      partner_user_id: string
      partner_email: string
      partner_display_name: string | null
      created_at: string
    }
    AccountabilityOverview: {
      incoming: components["schemas"]["AccountabilityInvite"][]
      outgoing: components["schemas"]["AccountabilityInvite"][]
      partners: components["schemas"]["AccountabilityPartner"][]
    }
    AccountabilityInviteCreate: {
      email: string
    }
    AccountabilityInviteActionResponse: {
      message: string
      status: "accepted" | "declined"
    }
    WeeklyReflection: {
      id: string
      user_id: string
      went_well: string
      blockers: string
      week_rating: number
      coach_recommendation: string
      created_at: string
    }
    WeeklyReflectionCreate: {
      went_well: string
      blockers: string
      /** 1–5 */
      week_rating: number
    }
    WeeklyReview: {
      start_date: string
      end_date: string
      total_tasks: number
      completed_tasks: number
      completion_rate: number
      completed_days: number
      overdue_tasks: number
      risk_level: "low" | "medium" | "high"
      recommendation: string
    }
    StarLog: {
      id: string
      user_id: string
      start_date: string
      end_date: string
      completed_tasks: number
      completed_days: number
      chapter_title: string
      chapter_body: string
      highlights: string[]
      is_fallback: boolean
      created_at: string
    }
    Badge: {
      key: string
      title: string
      description: string
      unlocked: boolean
      current: number
      target: number
    }
  }
}

export interface operations {
  get_user_profile: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": { star_points: number } } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  get_user_settings: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["UserProfile"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  update_user_settings: {
    parameters: { path: { user_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["UserSettingsUpdate"] } }
    responses: {
      200: { content: { "application/json": components["schemas"]["UserProfile"] } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  list_goals: {
    parameters: {
      path: { user_id: string }
      query?: { limit?: number; offset?: number }
    }
    responses: {
      200: { content: { "application/json": components["schemas"]["PaginatedGoalsResponse"] } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  create_goal: {
    parameters: { path: { user_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["GoalCreate"] } }
    responses: {
      202: { content: { "application/json": components["schemas"]["Goal"] } }
      403: { content: { "application/json": { detail: string } } }
      429: { content: { "application/json": { detail: string } } }
    }
  }
  get_goal: {
    parameters: { path: { goal_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["Goal"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  update_goal_status: {
    parameters: { path: { goal_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["GoalStatusUpdate"] } }
    responses: {
      200: { content: { "application/json": components["schemas"]["Goal"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  update_goal_progress: {
    parameters: { path: { goal_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["GoalProgressUpdate"] } }
    responses: {
      200: { content: { "application/json": components["schemas"]["Goal"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  delete_goal: {
    parameters: { path: { goal_id: string } }
    responses: {
      204: { content: never }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  trigger_rescue_sprint: {
    parameters: { path: { goal_id: string } }
    responses: {
      202: { content: { "application/json": components["schemas"]["Goal"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
      409: { content: { "application/json": { detail: string } } }
    }
  }
  list_goal_tasks: {
    parameters: { path: { goal_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["DailyTask"][] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  create_task: {
    parameters: { path: { goal_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["TaskCreate"] } }
    responses: {
      201: { content: { "application/json": components["schemas"]["DailyTask"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  reorder_tasks: {
    parameters: { path: { goal_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["TaskReorderRequest"] } }
    responses: {
      200: { content: { "application/json": components["schemas"]["DailyTask"][] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  complete_task: {
    parameters: { path: { task_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["TaskCompleteResponse"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  update_task: {
    parameters: { path: { task_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["TaskUpdate"] } }
    responses: {
      200: { content: { "application/json": components["schemas"]["DailyTask"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  delete_task: {
    parameters: { path: { task_id: string } }
    responses: {
      204: { content: never }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  regenerate_task: {
    parameters: { path: { task_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["EnergyResizeResponse"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  complete_milestone: {
    parameters: { path: { goal_id: string; milestone_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["Milestone"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  retry_milestone_generation: {
    parameters: { path: { goal_id: string; milestone_id: string } }
    responses: {
      202: { content: { "application/json": components["schemas"]["Milestone"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  start_coach_session: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["CoachSession"] } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  get_active_coach_session: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["CoachSession"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  send_coach_message: {
    parameters: { path: { session_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["CoachSendMessageRequest"] } }
    responses: {
      200: { content: { "application/json": components["schemas"]["CoachSendMessageResponse"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  list_rewards: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["Reward"][] } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  equip_reward: {
    parameters: { path: { reward_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["Reward"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  list_shop_rewards: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["ShopReward"][] } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  create_shop_reward: {
    parameters: { path: { user_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["ShopRewardCreate"] } }
    responses: {
      201: { content: { "application/json": components["schemas"]["ShopReward"] } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  update_shop_reward: {
    parameters: { path: { reward_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["ShopRewardUpdate"] } }
    responses: {
      200: { content: { "application/json": components["schemas"]["ShopReward"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  delete_shop_reward: {
    parameters: { path: { reward_id: string } }
    responses: {
      204: { content: never }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  redeem_shop_reward: {
    parameters: { path: { reward_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["ShopRewardRedeemResponse"] } }
      402: { content: { "application/json": { detail: string } } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  get_accountability_overview: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["AccountabilityOverview"] } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  send_accountability_invite: {
    parameters: { path: { user_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["AccountabilityInviteCreate"] } }
    responses: {
      200: { content: { "application/json": { message: string } } }
      403: { content: { "application/json": { detail: string } } }
      409: { content: { "application/json": { detail: string } } }
    }
  }
  accept_accountability_invite: {
    parameters: { path: { invite_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["AccountabilityInviteActionResponse"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  decline_accountability_invite: {
    parameters: { path: { invite_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["AccountabilityInviteActionResponse"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  create_weekly_reflection: {
    parameters: { path: { user_id: string } }
    requestBody: { content: { "application/json": components["schemas"]["WeeklyReflectionCreate"] } }
    responses: {
      201: { content: { "application/json": components["schemas"]["WeeklyReflection"] } }
      403: { content: { "application/json": { detail: string } } }
      429: { content: { "application/json": { detail: string } } }
    }
  }
  get_latest_weekly_reflection: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["WeeklyReflection"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  get_weekly_review: {
    parameters: {
      path: { user_id: string }
      query?: { days?: number }
    }
    responses: {
      200: { content: { "application/json": components["schemas"]["WeeklyReview"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  get_star_log: {
    parameters: {
      path: { user_id: string }
      query?: { days?: number }
    }
    responses: {
      200: { content: { "application/json": components["schemas"]["StarLog"] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  get_user_badges: {
    parameters: { path: { user_id: string } }
    responses: {
      200: { content: { "application/json": components["schemas"]["Badge"][] } }
      403: { content: { "application/json": { detail: string } } }
      404: { content: { "application/json": { detail: string } } }
    }
  }
  export_user_data: {
    parameters: {
      path: { user_id: string }
      query?: { format?: "json" | "csv" }
    }
    responses: {
      200: { content: { "application/json": Record<string, unknown> } }
      403: { content: { "application/json": { detail: string } } }
    }
  }
  delete_user: {
    parameters: { path: { user_id: string } }
    responses: {
      204: { content: never }
      403: { content: { "application/json": { detail: string } } }
    }
  }
}
